### ISSUE TITLE
Allow parameter optimization for specific streams

### ISSUE THREAD

**Issue by breznak** [htm-community/river-runner#3]
"The river-runner could be updated to swarm over some data first, then use the model params to rerun the same data through a live model. Right now it is just doing anomaly detection so not swarming at all." @rhyolight 

Swarming (parameter optimization) improves (interesting would be to see how much?) results of model predictions. 
- [x] get results on streams from generic model params (current)
- [ ] change `river-runner` to take specific model settings
- [ ] make `river-runner` do a quick swarming over a sample of the data

**Comment by rhyolight** [comment]
@breznak Isn't "get results on streams from generic model params (current)" done?

**Comment by breznak** [comment]
yes, ticked

**Comment by rhyolight** [comment]
@breznak I think this can be closed in favor of [Menorah](https://github.com/nupic-community/menorah), which achieves it.
